slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    use_odometry: true
    provide_odom_frame: true
    tf_buffer_duration: 30.0
    transform_timeout: 0.2
    scan_queue_size: 100

