slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # láser
    scan_topic: /scan
    resolution: 0.05
    max_laser_range: 12.0

    # SLAM en tiempo real
    mode: mapping
    use_odometry: true
    use_scan_matching: true

    # robustez de TF/colas
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    scan_queue_size: 100

    # publica map->odom (típico de SLAM); tu base publica odom->base_link
    provide_odom_frame: false

    # actualizaciones del mapa
    map_update_interval: 2.0
